/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package lavenstore.email;

import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import lavenstore.orders.OrderDTO;
import lavenstore.users.UserDTO;

public class BillEmail {

    public static String billEmail(UserDTO user, OrderDTO order, int quantity) {
        Timestamp timestamp = order.getDate();
        // Định dạng lại ngày theo dd/mm/yyyy
        Date date = new Date(timestamp.getTime());
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String time = dateFormat.format(date);

        DecimalFormat decimalFormat = new DecimalFormat("#,##,###");

        // Sử dụng phương thức format để định dạng số
        String thanhtoan = decimalFormat.format(order.getAmount());
        String billDetail = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Invoice</title>\n"
                + "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
                + "    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
                + "    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Vidaloka\">\n"
                + "    <style>\n"
                + "        * {\n"
                + "            box-sizing: border-box;\n"
                + "            font-family: 'Josefin Sans', sans-serif;\n"
                + "            padding: 0;\n"
                + "            margin: 0;\n"
                + "        }\n"
                + "        body{\n"
                + "            background-color: rgb(248, 248, 248);\n"
                + "        }\n"
                + "        p{\n"
                + "            padding: 0.7em 0;\n"
                + "            font-size: 20px !important;\n"
                + "        }\n"
                + "        .font-size{\n"
                + "            font-size: 18px;\n"
                + "        }\n"
                + "        .black{\n"
                + "            color: black;\n"
                + "        }\n"
                + "        .content {\n"
                + "            width: 100%;\n"
                + "            background-color: #D9D9D9;\n"
                + "        }\n"
                + "\n"
                + "        .box {\n"
                + "            width: 1000px;\n"
                + "            margin: auto;\n"
                + "        }\n"
                + "\n"
                + "        .banner {\n"
                + "            background-repeat: no-repeat;\n"
                + "            background-size: cover;\n"
                + "            background-image: url(https://cdn.discordapp.com/attachments/1202620106140680202/1215702834419601459/The_LAVEN_STORE.png?ex=65fdb67e&is=65eb417e&hm=808bfcb44759b2e2d14f4a527db434afae181c0d7d38de35731a0154719722a5&);\n"
                + "            text-align: center;\n"
                + "            height: 7em;\n"
                + "        }\n"
                + "\n"
                + "        .banner h1 {\n"
                + "            font-family: Arial, Helvetica, sans-serif;\n"
                + "            color: #8B6E4A;\n"
                + "            padding-top: 1em;\n"
                + "            font-size: 30px;\n"
                + "        }\n"
                + "\n"
                + "        .w-25 {\n"
                + "            width: 25%;\n"
                + "        }\n"
                + "\n"
                + "        .w-75 {\n"
                + "            width: 75%;\n"
                + "        }\n"
                + "\n"
                + "        .w-80 {\n"
                + "            width: 80%;\n"
                + "        }\n"
                + "\n"
                + "        .w-100 {\n"
                + "            width: 100%;\n"
                + "        }\n"
                + "\n"
                + "        .body {\n"
                + "            background-color: #F5F5F5;\n"
                + "            padding-top: 10px;\n"
                + "        }\n"
                + "\n"
                + "        .tile-customer {\n"
                + "            padding: 0.8em 0;\n"
                + "        }\n"
                + "\n"
                + "        .title-order {\n"
                + "            font-size: 18px;\n"
                + "            font-family: 'Times New Roman', Times, serif;\n"
                + "        }\n"
                + "\n"
                + "        .spec {\n"
                + "            color: #8B6E4A;\n"
                + "            font-weight: bold;\n"
                + "        }\n"
                + "\n"
                + "        .title-order a {\n"
                + "            text-decoration: none;\n"
                + "            color: #8B6E4A;\n"
                + "            font-weight: bold;\n"
                + "        }\n"
                + "\n"
                + "        .title-order span {\n"
                + "            color: #8B6E4A;\n"
                + "            font-weight: bold;\n"
                + "        }\n"
                + "\n"
                + "        .tile-customer {\n"
                + "            color: #8B6E4A;\n"
                + "            font-weight: bold;\n"
                + "            font-size: 20px;\n"
                + "        }\n"
                + "\n"
                + "        .table-customer {\n"
                + "            padding: 1em 1em;\n"
                + "        }\n"
                + "\n"
                + "        .table-info-customer {\n"
                + "            color: #B8860B;\n"
                + "            font-weight: bold;\n"
                + "        }\n"
                + "\n"
                + "        .row-table-customer {\n"
                + "            padding: 0.6em 0;\n"
                + "        }\n"
                + "\n"
                + "        .table-content-customer {\n"
                + "            color: black;\n"
                + "            font-weight: 600;\n"
                + "        }\n"
                + "\n"
                + "        .email-auto {\n"
                + "            color: #696969;\n"
                + "            font-style: italic;\n"
                + "            font-weight: 500;\n"
                + "            font-size: 10px;\n"
                + "            padding: 0.2em 0;\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "    <div class=\"content\">\n"
                + "        <div class=\"box\">\n"
                + "            <div class=\"banner\">\n"
                + "                <h1 class=\"\">The LAVEN STORE</h1>\n"
                + "            </div>\n"
                + "            <div class=\"body pt-3\">\n"
                + "                <div class=\"\" style=\"padding: 20px;\">\n"
                + "                    <p class=\"title-order spec\">Kính gửi quý khách hàng: "+user.getFullName()+"</p>\n"
                + "                    <p class=\"title-order black\">Xin trân trọng cảm ơn quý khách đã mua hàng và sử dụng dịch vụ tại <a\n"
                + "                            href=\"#\">The LAVEN STORE</a></p>\n"
                + "                    <p class=\"title-order mb-5 black\">Chúng tôi phát hành hóa đơn cho đơn hàng <span>#"+order.getOrderCode()+"</span> với\n"
                + "                        các thông tin như sau:</p>\n"
                + "                    <h3 class=\"tile-customer\">THÔNG TIN KHÁCH HÀNG:</h3>\n"
                + "                    <hr>\n"
                + "                    <div class=\"table-customer\">\n"
                + "                        <table class=\"w-100\">\n"
                + "                            <tr>\n"
                + "                                <td class=\"w-25 row-table-customer\">\n"
                + "                                    <div class=\"table-info-customer font-size\">Khách hàng</div>\n"
                + "                                </td>\n"
                + "                                <td class=\"w-75\"><span class=\"table-content-customer font-size\">"+user.getFullName()+"</span></td>\n"
                + "                            </tr>\n"
                + "                            <tr>\n"
                + "                                <td class=\"w-25 row-table-customer\"><span class=\"table-info-customer font-size\">Mail</span></td>\n"
                + "                                <td><span class=\"table-content-customer font-size\">"+user.getEmail()+"</span></td>\n"
                + "                            </tr>\n"
                + "                            <tr>\n"
                + "                                <td class=\"w-25 row-table-customer\"><span class=\"table-info-customer font-size\">Số điện thoại</span></td>\n"
                + "                                <td><span class=\"table-content-customer font-size\">"+user.getPhoneNumber()+"</span></td>\n"
                + "                            </tr>\n"
                + "                            <tr>\n"
                + "                                <td class=\"w-25 row-table-customer\"><span class=\"table-info-customer font-size\">Địa Chỉ</span></td>\n"
                + "                                <td class=\"\"><span class=\"table-content-customer font-size\">"+user.getAddress()+"</span></td>\n"
                + "                            </tr>\n"
                + "                        </table>\n"
                + "                    </div>\n"
                + "                    <h3 class=\"tile-customer\">THÔNG TIN HÓA ĐƠN:</h3>\n"
                + "                    <hr>\n"
                + "                    <div class=\"table-customer\">\n"
                + "                        <table class=\"w-100\">\n"
                + "                            <tr>\n"
                + "                                <td class=\"w-25 row-table-customer\"><span class=\"table-info-customer font-size\">Số hóa đơn</span></td>\n"
                + "                                <td class=\"\"><span class=\"table-content-customer font-size\">#"+order.getOrderCode()+"</span></td>\n"
                + "                            </tr>\n"
                + "                            <tr>\n"
                + "                                <td class=\"w-25 row-table-customer\"><span class=\"table-info-customer font-size\">Ngày tạo hóa đơn</span></td>\n"
                + "                                <td class=\"\"><span class=\"table-content-customer font-size\">"+time+"</span></td>\n"
                + "                            </tr>\n"
                + "                            <tr>\n"
                + "                                <td class=\"w-25 row-table-customer\"><span class=\"table-info-customer font-size\">Số lượng sản phẩm</span></td>\n"
                + "                                <td class=\"\"><span class=\"table-content-customer font-size\">"+quantity+"</span></td>\n"
                + "                            </tr>\n"
                + "                            <tr>\n"
                + "                                <td class=\"w-25 row-table-customer\"><span class=\"table-info-customer font-size\">Số tiền thanh toán</span></td>\n"
                + "                                <td class=\"\"><span class=\"table-content-customer font-size\">"+thanhtoan+"</span></td>\n"
                + "                            </tr>\n"
                + "                            <tr>\n"
                + "                                <td class=\"w-25 row-table-customer\"><span class=\"table-info-customer font-size\">Phương thức thanh toán</span>\n"
                + "                                </td>\n"
                + "                                <td class=\"\"><span class=\"table-content-customer font-size\">"+order.getPaymentMethod()+"</span></td>\n"
                + "                            </tr>\n"
                + "                            <tr>\n"
                + "                                <td class=\"w-25 row-table-customer\"><span class=\"table-info-customer font-size\">Ghi chú</span>\n"
                + "                                </td>\n"
                + "                                <td class=\"\"><span class=\"table-content-customer font-size\">"+order.getNote()+"</span></td>\n"
                + "                            </tr>\n"
                + "                        </table>\n"
                + "                    </div>\n"
                + "                    <p class=\"title-order black\">Cảm ơn quý khách đã tin tưởng và lựa chọn mua hàng tại <span\n"
                + "                            class=\"spec\">The Laven Store</span></p>\n"
                + "                    <p class=\"email-auto\">Đây là Email tự động, quý khách vui lòng không trả lời Email này.\n"
                + "                    </p>\n"
                + "                    <p class=\"email-auto\">Trân trọng.</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "        </div>\n"
                + "    </div>\n"
                + "</body>\n"
                + "\n"
                + "</html>";
        return billDetail;
    }
    
}
